add_requires("cxxopts")

target("test-pp-reduce")
    set_kind("binary")
    set_default(false)
    set_group("test")
    add_files("*.cpp")
    add_packages("fmt", "slang-rhi", "cxxopts")
    add_deps("llc")
    add_tests("default")
