add_requires("stb")

target("llc")
    set_kind("static")
    add_files("source/**/*.cpp")
    add_files("shader/*.slang", "shader/**/*.slang", {slang_embed = true})
    add_includedirs("source", {public = true})
    add_packages("slang-rhi", "fmt", "stb")
    add_packages("glm", {public = true})
    add_rules("slang", {include_dirs = {"shader"}})
